#!/usr/bin/env bash

if [ $# -ne 3 ];
then
    echo "Usage: map_vg N_THREADS VG_BASE_FILE_NAME INPUT_FASTA_FILE"
    exit
fi

threads=$1
vg_base=$2
reads=$3

vg map -d $vg_base -f $reads -t $threads --refpos-table > vg.pos

