#!/usr/bin/env bash

chromosomes=$1
threads=$2
obg_graph_dir=$3
sim_fasta=$4
n_reads=$5
linear_ref_bonus=$6
bwa_index=$7
minimap_fasta=$8

echo "Starting two step"
date
echo "Rough initial mapping"
bwa-mem2 mem -t $threads $bwa_index simulated_reads.fa | awk '$2 < 256' | cut -f 1-15 > rough_linear.sam
date

echo "MDZ align"
time rough_graph_mapper mdz_align_bam -b rough_linear.sam -d $obg_graph_dir -o mdzaligned -c $chromosomes
echo "Done mdz align. Predicting path"
date

time two_step_graph_mapper predict_path -t $threads --linear-ref-bonus $linear_ref_bonus -d $obg_graph_dir -a mdzaligned -c $chromosomes -o predicted_path --input-is-edgecounts True

echo "Run tuned bwa"
date
# The following maps and splits by chromosomes in one line (avoiding disk write)
map_linear $threads $bwa_index $minimap_fasta $sim_fasta | two_step_graph_mapper convert_to_reference_positions -d $obg_graph_dir -c $chromosomes > two_step_graph_mapper_on_reference.sam

merge_with_rough rough_linear.sam two_step_graph_mapper_on_reference.sam > two_step_final.sam
