#!/usr/bin/env bash

if [ $# -ne 8  ];
then
    echo "Usage: two_step_map chromosomes n_threads obg_graph_dir input_fasta n_reads linear_ref_bonus bwa_index minimap_fasta"
    exit
fi

chromosomes=$1
threads=$2
obg_graph_dir=$3
map_fasta=$4
n_reads=$5
linear_ref_bonus=$6
bwa_index=$7
minimap_fasta=$8

echo "Starting two step"
date
echo "Rough initial mapping"
bwa-mem2 mem -t $threads $bwa_index $map_fasta > rough_linear.sam
date

echo "MDZ align"
time rough_graph_mapper mdz_align_bam -b rough_linear.sam -d $obg_graph_dir -o mdzaligned -c $chromosomes
echo "Done mdz align. Predicting path"
date

time two_step_graph_mapper predict_path -t $threads --linear-ref-bonus $linear_ref_bonus -d $obg_graph_dir -a mdzaligned -c $chromosomes -o predicted_path --input-is-edgecounts True

echo "Run tuned bwa"
date
# The following maps and splits by chromosomes in one line (avoiding disk write)
map_linear $threads predicted_path.fa predicted_path.fa $map_fasta | two_step_graph_mapper convert_to_reference_positions -d $obg_graph_dir -c $chromosomes > two_step_graph_mapper_on_reference.sam

echo "Done map linear"
date

echo "Merge with rough"
rough_graph_mapper merge_sams --only-score-lowering True two_step_graph_mapper_on_reference.sam rough_linear.sam > two_step_final.sam
#grep -v '^@' rough_linear.sam | cut -f 1-15 | awk '$2 < 256' | merge_sams_with_rough - two_step_graph_mapper_on_reference.sam > two_step_final.sam

date
echo "Done with all."
